config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :scaffold_resources
  root 'scaffold_resources#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scaffold_resource.rb
# frozen_string_literal: true

class ScaffoldResource < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/scaffold_resources_controller.rb
# frozen_string_literal: true

class ScaffoldResourcesController < ApplicationController
  before_action :set_scaffold_resource, only: %i[show edit update destroy]

  # GET /scaffold_resources or /scaffold_resources.json
  def index
    @scaffold_resources = ScaffoldResource.all
  end

  # GET /scaffold_resources/1 or /scaffold_resources/1.json
  def show; end

  # GET /scaffold_resources/new
  def new
    @scaffold_resource = ScaffoldResource.new
  end

  # GET /scaffold_resources/1/edit
  def edit; end

  # POST /scaffold_resources or /scaffold_resources.json
  def create
    @scaffold_resource = ScaffoldResource.new(scaffold_resource_params)

    respond_to do |format|
      if @scaffold_resource.save
        format.html do
          redirect_to scaffold_resource_url(@scaffold_resource), notice: 'Scaffold resource was successfully created.'
        end
        format.json { render :show, status: :created, location: @scaffold_resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scaffold_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scaffold_resources/1 or /scaffold_resources/1.json
  def update
    respond_to do |format|
      if @scaffold_resource.update(scaffold_resource_params)
        format.html do
          redirect_to scaffold_resource_url(@scaffold_resource), notice: 'Scaffold resource was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @scaffold_resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scaffold_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scaffold_resources/1 or /scaffold_resources/1.json
  def destroy
    @scaffold_resource.destroy

    respond_to do |format|
      format.html { redirect_to scaffold_resources_url, notice: 'Scaffold resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_scaffold_resource
    @scaffold_resource = ScaffoldResource.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def scaffold_resource_params
    params.require(:scaffold_resource).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/scaffold_resources_helper.rb
# frozen_string_literal: true

module ScaffoldResourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsbytesResearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scaffold_resources/_form.html.erb
<%= form_with(model: scaffold_resource, local: true) do |form| %>
  <% if scaffold_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scaffold_resource.errors.count, "error") %> prohibited this scaffold_resource from being saved:</h2>

      <ul>
        <% scaffold_resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scaffold_resources/edit.html.erb
<h1>Editing Scaffold Resource</h1>

<%= render 'form', scaffold_resource: @scaffold_resource %>

<%= link_to 'Show', @scaffold_resource %> |
<%= link_to 'Back', scaffold_resources_path %>

app/views/scaffold_resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scaffold Resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scaffold_resources.each do |scaffold_resource| %>
      <tr>
        <td><%= scaffold_resource.name %></td>
        <td><%= scaffold_resource.description %></td>
        <td><%= link_to 'Show', scaffold_resource %></td>
        <td><%= link_to 'Edit', edit_scaffold_resource_path(scaffold_resource) %></td>
        <td><%= link_to 'Destroy', scaffold_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scaffold Resource', new_scaffold_resource_path %>

app/views/scaffold_resources/new.html.erb
<h1>New Scaffold Resource</h1>

<%= render 'form', scaffold_resource: @scaffold_resource %>

<%= link_to 'Back', scaffold_resources_path %>

app/views/scaffold_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scaffold_resource.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scaffold_resource.description %>
</p>

<%= link_to 'Edit', edit_scaffold_resource_path(@scaffold_resource) %> |
<%= link_to 'Back', scaffold_resources_path %>